apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password

# In the image, we have specified "mongo", so it will fetch the latest mongo image from the docker hub.
# These require 2 env. variables called MONGO_INITDB_ROOT_USERNAME & MONGO_INITDB_ROOT_PASSWORD . To get these values we will create a Secret from where we will reference that value.
# secretKeyRef.name : specifies the name of the secret (which we have defined in Step 2)
# secretKeyRef.key : specifies the key name which we have declared under the data section in Step 2.
# Please note: Secret must be created before the deployment because this deployment step has dependency over the Secret step.

