apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=

# Values inside the data are not plain text this should be encrypted in some way. Storing the data in a Secret component doesn't automatically make it secure.
# We can easily generate the base64 encoded for any plain text using the following command:
#  echo -n 'plain text' | base64  
#// Output: cGxhaW4gdGV4dA==
